package com.bayudwiyansatria.spring.model.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

/**
 * HomeEntity
 * <p>
 * This class represents the Home entity, which is typically used to store a simple message
 * associated with the Home entity. It is annotated with {@code @Entity} to indicate that it is a
 * JPA (Java Persistence API) entity, meaning it will be mapped to a database table.
 * </p>
 *
 * <p>The {@code id} field serves as the primary key and is automatically generated by the
 * database.</p>
 *
 * <p>The {@code message} field holds the message associated with the Home entity.</p>
 *
 * <p>The {@code toString()} method formats the entity as a string, combining the ID and message
 * for easy display.</p>
 *
 * <p>The entity is annotated with the Lombok {@code @Data} annotation, which automatically
 * generates boilerplate code such as getters, setters, equals, hashCode, and toString methods.</p>
 *
 * @author Bayu Dwiyan Satria
 * @version 0.0.1
 * @since 0.0.1
 */
@Data
@Entity
public class HomeEntity {

    /**
     * The unique identifier for the Home entity. It is generated automatically by the database.
     * <p>
     * This field is annotated with {@code @Id} to indicate it is the primary key of the entity. It
     * is also annotated with {@code @GeneratedValue(strategy = GenerationType.AUTO)} to
     * automatically generate the value of this field.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * The message associated with the Home entity.
     * <p>
     * This field stores the message that is associated with the entity. It can be used to hold
     * simple textual information related to the Home entity.
     * </p>
     */
    private String message;

    /**
     * {@inheritDoc}
     * <p>
     * This method overrides the {@code toString()} method to provide a custom string representation
     * of the entity. The output includes the {@code id} and {@code message}.
     * </p>
     *
     * @return a formatted string representation of the entity.
     */
    @Override
    public String toString() {
        return String.format("User: %s %s", id, message);
    }
}
