{{- if .Values.rbac.create }}
{{- range .Values.rbac.targetNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-apiclient.fullname" $ }}-secret-reconciler
  namespace: {{ . }}
  labels:
    {{- include "kube-apiclient.labels" $ | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
---
{{- end }}
{{- end }}
